/*
 * Aifs api
 *
 * aifs api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type RawDataListItem struct {

	// the id of the raw data
	RawDataId string `json:"rawDataId,omitempty"`

	Url string `json:"url,omitempty"`
}
