/*
 * Aifs api
 *
 * aifs api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type CopyAnnotationTemplate200Response struct {

	// annotation template id of the copied annotation template
	AnnotationTemplateId string `json:"annotationTemplateId,omitempty"`
}
