/*
 * Aifs api
 *
 * aifs api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type ArtifactLocations struct {

	DataViewId string `json:"dataViewId,omitempty"`

	ViewType DataViewType `json:"viewType,omitempty"`

	DataItems []S3StorageInner `json:"dataItems,omitempty"`
}
