/*
 * Aifs api
 *
 * aifs api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// RawDataType : the type of raw data
type RawDataType string

// List of RawDataType
const (
	IMAGE RawDataType = "image"
	TEXT RawDataType = "text"
	RGBD RawDataType = "rgbd"
	POINTS_3D RawDataType = "points-3d"
)
