/*
 * Aifs api
 *
 * aifs api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type FilterAnnotationsInDataViewResponse struct {

	// the id of the filtered annotation view.
	AnnotationViewId string `json:"annotationViewId,omitempty"`
}
