/*
 * Aifs api
 *
 * aifs api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type GetAnnotationsInDataView200Response struct {

	AnnotationTemplateId string `json:"annotationTemplateId,omitempty"`

	AnnotationTemplateType string `json:"annotationTemplateType,omitempty"`

	AnnotationList []AnnotationListItem `json:"annotationList,omitempty"`
}
