/*
 * Aifs api
 *
 * aifs api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"os"
)

type ImageData struct {

	Format string `json:"format,omitempty"`

	Data *os.File `json:"data,omitempty"`
}
