/*
 * Aifs api
 *
 * aifs api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// ZipFormat : the structure of the files in zip file
type ZipFormat string

// List of ZipFormat
const (
	IMAGE_CLASSIFICATION ZipFormat = "image-classification"
	RGBD_BOUNDING_BOX_2D_AND_3D ZipFormat = "rgbd-bounding-box-2d-and-3d"
	IMAGE_SEGMENTATION_MASKS ZipFormat = "image-segmentation-masks"
	OCR ZipFormat = "ocr"
	COCO ZipFormat = "coco"
	RAW_DATA_IMAGES ZipFormat = "raw-data-images"
	SAM ZipFormat = "sam"
	POINTS_3D_ZIP ZipFormat = "points-3d-zip"
)
