/*
 * Aifs api
 *
 * aifs api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type DivideRawDataDataViewResponseInner struct {

	Name string `json:"name,omitempty"`

	DataViewId string `json:"dataViewId,omitempty"`

	ItemCount int32 `json:"itemCount,omitempty"`
}
