/*
 * Aifs api
 *
 * aifs api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// UploadAnnotationFormat : the format of the data
type UploadAnnotationFormat string

// List of UploadAnnotationFormat
const (
	ALL_ANNOTATION_SINGLE_FILE_LOCAL UploadAnnotationFormat = "all-annotation-single-file-local"
	PER_ANNOTATION_PER_FILE_LOCAL UploadAnnotationFormat = "per-annotation-per-file-local"
)
