/*
 * Aifs api
 *
 * aifs api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type AnnotationDataInner struct {

	DataItemId string `json:"dataItemId,omitempty"`

	Labels []string `json:"labels,omitempty"`

	// text format annotation data
	TextData string `json:"textData,omitempty"`
}
