/*
 * Aifs api
 *
 * aifs api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type CreateDataViewSuccessResp struct {

	DataViewId string `json:"dataViewId,omitempty"`
}
