/*
 * Aifs api
 *
 * aifs api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type MergeDataViewsRequest struct {

	// name of the merged data view
	Name string `json:"name,omitempty"`

	// description of the merged data view
	Description string `json:"description,omitempty"`

	DataViewIdList []string `json:"dataViewIdList,omitempty"`
}
