/*
 * Aifs api
 *
 * aifs api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type RawDataHashListInner struct {

	RawDataId string `json:"rawDataId,omitempty"`

	Sha256 string `json:"sha256,omitempty"`
}
