/*
 * Aifs api
 *
 * aifs api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type DataViewListItem struct {

	// the id of the data view
	Id string `json:"id,omitempty"`

	// the name of the data view
	Name string `json:"name,omitempty"`

	ViewType DataViewType `json:"viewType,omitempty"`

	RawDataType RawDataType `json:"rawDataType,omitempty"`

	// if data view is an annotation view, it has annotation template id
	AnnotationTemplateId string `json:"annotationTemplateId,omitempty"`

	// if data view is an annotation view, it has annotation template type
	AnnotationTemplateType string `json:"annotationTemplateType,omitempty"`

	// Unix timestamp in ms
	CreateAt int64 `json:"createAt,omitempty"`
}
