/*
 * Aifs api
 *
 * aifs api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type DataViewType string

// List of DataViewType
const (
	RAW_DATA DataViewType = "raw-data"
	ANNOTATION DataViewType = "annotation"
	MODEL DataViewType = "model"
	DATASET_ZIP DataViewType = "dataset-zip"
	ARTIFACT DataViewType = "artifact"
)
