/*
 * Aifs api
 *
 * aifs api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// AnnotationListItem - the result of get annotation list
type AnnotationListItem struct {

	// the id of the raw data
	RawDataId string `json:"rawDataId,omitempty"`

	// the id of the annotation data item
	DataItemId string `json:"dataItemId,omitempty"`

	Url string `json:"url,omitempty"`

	Labels []string `json:"labels,omitempty"`
}
