/*
 * Aifs api
 *
 * aifs api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type DownloadResponse struct {

	// the directory where to put the data
	Directory string `json:"directory,omitempty"`
}
