/*
 * Aifs api
 *
 * aifs api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type DivideRawDataDataViewRequestInner struct {

	Name string `json:"name,omitempty"`

	Description string `json:"description,omitempty"`

	Ratio int32 `json:"ratio,omitempty"`
}
