/*
 * Aifs api
 *
 * aifs api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type AnnotationTemplateListItem struct {

	// the id of the annotation template
	Id string `json:"id,omitempty"`

	// name of the annotation template
	Name string `json:"name,omitempty"`

	// Unix timestamp in ms
	CreateAt int64 `json:"createAt,omitempty"`

	// the type of the annotation template
	Type string `json:"type,omitempty"`

	// the number of labels annotation template has
	LabelCount int32 `json:"labelCount,omitempty"`
}
