/*
 * Aifs api
 *
 * aifs api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type DataViewDetails struct {

	// the id of the data view
	Id string `json:"id,omitempty"`

	// the name of the data view
	Name string `json:"name,omitempty"`

	ViewType DataViewType `json:"viewType,omitempty"`

	// the description of the data view
	Description string `json:"description,omitempty"`

	RawDataType RawDataType `json:"rawDataType,omitempty"`

	// if data view is an annotation view, it has annotation template type
	AnnotationTemplateType string `json:"annotationTemplateType,omitempty"`

	// Unix timestamp in ms
	CreateAt int64 `json:"createAt,omitempty"`

	Progress float32 `json:"progress,omitempty"`

	CommitId string `json:"commitId,omitempty"`

	Status string `json:"status,omitempty"`

	ZipFormat ZipFormat `json:"zipFormat,omitempty"`

	TrainRawDataViewId string `json:"trainRawDataViewId,omitempty"`

	TrainAnnotationViewId string `json:"trainAnnotationViewId,omitempty"`

	ValRawDataViewId string `json:"valRawDataViewId,omitempty"`

	ValAnnotationViewId string `json:"valAnnotationViewId,omitempty"`

	AnnotationTemplateId string `json:"annotationTemplateId,omitempty"`

	RawDataViewId string `json:"rawDataViewId,omitempty"`

	AnnotationViewId string `json:"annotationViewId,omitempty"`
}
