/*
 * Aifs api
 *
 * aifs api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type GetRawDataInDataView200Response struct {

	RawDataType RawDataType `json:"rawDataType,omitempty"`

	RawDataList []RawDataListItem `json:"rawDataList,omitempty"`
}
