/*
 * Aifs api
 *
 * aifs api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package apigin

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

// Route is the information for every URI.
type Route struct {
	// Name is the name of this Route.
	Name string
	// Method is the string for the HTTP method. ex) GET, POST etc..
	Method string
	// Pattern is the pattern of the URI.
	Pattern string
	// HandlerFunc is the handler function of this route.
	HandlerFunc gin.HandlerFunc
}

// Routes is the list of the generated Route.
type Routes []Route

// NewRouter returns a new router.
func NewRouter() *gin.Engine {
	router := gin.Default()
	router.MaxMultipartMemory = 32 << 20 // 32 MiB
	router.Use(ErrorHandler())
	router.Use(PanicHandler())
	for _, route := range routes {
		switch route.Method {
		case http.MethodGet:
			router.GET(route.Pattern, route.HandlerFunc)
		case http.MethodPost:
			router.POST(route.Pattern, route.HandlerFunc)
		case http.MethodPut:
			router.PUT(route.Pattern, route.HandlerFunc)
		case http.MethodPatch:
			router.PATCH(route.Pattern, route.HandlerFunc)
		case http.MethodDelete:
			router.DELETE(route.Pattern, route.HandlerFunc)
		}
	}

	return router
}

// Index is the index handler.
func Index(c *gin.Context) {
	c.String(http.StatusOK, "Hello World!")
}

var routes = Routes{
	{
		"Index",
		http.MethodGet,
		"/api/open/v1/",
		Index,
	},

	{
		"CopyAnnotationTemplate",
		http.MethodPost,
		"/api/open/v1/annotation-templates/:annotationTemplateId/copy",
		CopyAnnotationTemplate,
	},

	{
		"CreateAnnotationTemplate",
		http.MethodPost,
		"/api/open/v1/annotation-templates",
		CreateAnnotationTemplate,
	},

	{
		"DeleteAnnotationTemplate",
		http.MethodDelete,
		"/api/open/v1/annotation-templates/:annotationTemplateId",
		DeleteAnnotationTemplate,
	},

	{
		"GetAnnoTemplateDetails",
		http.MethodGet,
		"/api/open/v1/annotation-templates/:annotationTemplateId/details",
		GetAnnoTemplateDetails,
	},

	{
		"GetAnnoTemplateList",
		http.MethodGet,
		"/api/open/v1/annotation-templates",
		GetAnnoTemplateList,
	},

	{
		"UpdateAnnotationTemplate",
		http.MethodPut,
		"/api/open/v1/annotation-templates",
		UpdateAnnotationTemplate,
	},

	{
		"GetAnnoTemplateTypeList",
		http.MethodGet,
		"/api/open/v1/annotation-template-types",
		GetAnnoTemplateTypeList,
	},

	{
		"CreateDataView",
		http.MethodPost,
		"/api/open/v1/data-views",
		CreateDataView,
	},

	{
		"DeleteDataItemInDataView",
		http.MethodDelete,
		"/api/open/v1/data-views/:dataViewId/data-items",
		DeleteDataItemInDataView,
	},

	{
		"DeleteDataView",
		http.MethodDelete,
		"/api/open/v1/data-views/:dataViewId",
		DeleteDataView,
	},

	{
		"DivideDataView",
		http.MethodPost,
		"/api/open/v1/data-views/:dataViewId/raw-data-divide",
		DivideDataView,
	},

	{
		"FilterAnnotationsInDataView",
		http.MethodPost,
		"/api/open/v1/data-views/:dataViewId/annotation-filter",
		FilterAnnotationsInDataView,
	},

	{
		"GetAllAnnotationDataInDataView",
		http.MethodGet,
		"/api/open/v1/data-views/:dataViewId/annotation-data",
		GetAllAnnotationDataInDataView,
	},

	{
		"GetAllAnnotationLocationsInDataView",
		http.MethodGet,
		"/api/open/v1/data-views/:dataViewId/annotation-locations",
		GetAllAnnotationLocationsInDataView,
	},

	{
		"GetAllRawDataLocationsInDataView",
		http.MethodGet,
		"/api/open/v1/data-views/:dataViewId/raw-data-locations",
		GetAllRawDataLocationsInDataView,
	},

	{
		"GetAnnotationsInDataView",
		http.MethodGet,
		"/api/open/v1/data-views/:dataViewId/annotations",
		GetAnnotationsInDataView,
	},

	{
		"GetArtifactLocationsInDataView",
		http.MethodGet,
		"/api/open/v1/data-views/:dataViewId/artifact-locations",
		GetArtifactLocationsInDataView,
	},

	{
		"GetDataViewDetails",
		http.MethodGet,
		"/api/open/v1/data-views/:dataViewId/details",
		GetDataViewDetails,
	},

	{
		"GetDataViewList",
		http.MethodGet,
		"/api/open/v1/data-views",
		GetDataViewList,
	},

	{
		"GetDataViewStatistics",
		http.MethodGet,
		"/api/open/v1/data-views/:dataViewId/statistics",
		GetDataViewStatistics,
	},

	{
		"GetDatasetZipLocationInDataView",
		http.MethodGet,
		"/api/open/v1/data-views/:dataViewId/dataset-zip-location",
		GetDatasetZipLocationInDataView,
	},

	{
		"GetModelDataLocationsInDataView",
		http.MethodGet,
		"/api/open/v1/data-views/:dataViewId/model-data-locations",
		GetModelDataLocationsInDataView,
	},

	{
		"GetRawDataHashListInDataView",
		http.MethodGet,
		"/api/open/v1/data-views/:dataViewId/raw-data-hash-list",
		GetRawDataHashListInDataView,
	},

	{
		"GetRawDataInDataView",
		http.MethodGet,
		"/api/open/v1/data-views/:dataViewId/raw-data",
		GetRawDataInDataView,
	},

	{
		"HardDeleteDataView",
		http.MethodDelete,
		"/api/open/v1/data-views/:dataViewId/hard-delete",
		HardDeleteDataView,
	},

	{
		"MergeDataViews",
		http.MethodPost,
		"/api/open/v1/data-views/merge",
		MergeDataViews,
	},

	{
		"MergeDataViewsToCrurrent",
		http.MethodPost,
		"/api/open/v1/data-views/:dataViewId/merge",
		MergeDataViewsToCrurrent,
	},

	{
		"MoveDataViewItems",
		http.MethodPost,
		"/api/open/v1/data-views/move",
		MoveDataViewItems,
	},

	{
		"UpdateDatasetZipView",
		http.MethodPut,
		"/api/open/v1/data-views/:dataViewId/dataset-zip",
		UpdateDatasetZipView,
	},

	{
		"UploadAnnotationToDataView",
		http.MethodPost,
		"/api/open/v1/data-views/:dataViewId/annotations",
		UploadAnnotationToDataView,
	},

	{
		"UploadDatasetZipToDataView",
		http.MethodPost,
		"/api/open/v1/data-views/:dataViewId/dataset-zip",
		UploadDatasetZipToDataView,
	},

	{
		"UploadFileToDataView",
		http.MethodPost,
		"/api/open/v1/data-views/:dataViewId/artifact",
		UploadFileToDataView,
	},

	{
		"UploadModelDataToDataView",
		http.MethodPost,
		"/api/open/v1/data-views/:dataViewId/model",
		UploadModelDataToDataView,
	},

	{
		"UploadRawDataToDataView",
		http.MethodPost,
		"/api/open/v1/data-views/:dataViewId/raw-data",
		UploadRawDataToDataView,
	},
}
