/*
 * Aifs api
 *
 * aifs api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

// CopyAnnotationTemplate - Copy an annotation template
func CopyAnnotationTemplate(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// CreateAnnotationTemplate - Create an annotation template
func CreateAnnotationTemplate(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// DeleteAnnotationTemplate - Delete an annotation template
func DeleteAnnotationTemplate(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// GetAnnoTemplateDetails - Get annotation template details
func GetAnnoTemplateDetails(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// GetAnnoTemplateList - Get annotation template list
func GetAnnoTemplateList(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// UpdateAnnotationTemplate - Update an annotation template
func UpdateAnnotationTemplate(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}
