/*
 * Aifs api
 *
 * aifs api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

// GetAnnoTemplateTypeList - Get annotation template type list
func GetAnnoTemplateTypeList(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}
