/*
 * Aifs api
 *
 * aifs api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package apigin

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

// CreateDataView - Create a data view
func CreateDataView(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// DeleteDataItemInDataView - Delete data item in a data view
func DeleteDataItemInDataView(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// DeleteDataView - Delete a data view
func DeleteDataView(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// DivideDataView - Divide data view
func DivideDataView(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// FilterAnnotationsInDataView - Filter annotations in a data view
func FilterAnnotationsInDataView(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// GetAllAnnotationDataInDataView - Get all annotation data in a data view
func GetAllAnnotationDataInDataView(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// GetAllAnnotationLocationsInDataView - Get all annotation locations in a data view
func GetAllAnnotationLocationsInDataView(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// GetAllRawDataLocationsInDataView - Get all raw data locations in a data view
func GetAllRawDataLocationsInDataView(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// GetAnnotationsInDataView - Get data view annotations
func GetAnnotationsInDataView(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// GetArtifactLocationsInDataView - Get files' locations in artifact data view
func GetArtifactLocationsInDataView(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// GetDataViewDetails - Get data view details
func GetDataViewDetails(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// GetDataViewList - Get data view list
func GetDataViewList(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// GetDataViewStatistics - Get data view statistics
func GetDataViewStatistics(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// GetDatasetZipLocationInDataView - Get dataset zip's location in a data view
func GetDatasetZipLocationInDataView(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// GetModelDataLocationsInDataView - Get all model data locations in a data view
func GetModelDataLocationsInDataView(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// GetRawDataHashListInDataView - Get data view raw data hash list
func GetRawDataHashListInDataView(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// GetRawDataInDataView - Get data view raw data
func GetRawDataInDataView(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// HardDeleteDataView - Hard delete a data view
func HardDeleteDataView(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// MergeDataViews - Merge data views
func MergeDataViews(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// MergeDataViewsToCrurrent - Merge data views
func MergeDataViewsToCrurrent(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// MoveDataViewItems - Move data items between data views
func MoveDataViewItems(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// UpdateDatasetZipView - Update a dataset-zip view meta
func UpdateDatasetZipView(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// UploadAnnotationToDataView - Upload annotations to data view
func UploadAnnotationToDataView(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// UploadDatasetZipToDataView - Upload dataset zip
func UploadDatasetZipToDataView(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// UploadFileToDataView - Upload file to data view
func UploadFileToDataView(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// UploadModelDataToDataView - Upload model data to data view
func UploadModelDataToDataView(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// UploadRawDataToDataView - Upload raw data to data view
func UploadRawDataToDataView(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}
